name: CI

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Checkers
      run: pip install black isort flake8
    - name: black
      run: black --check .
    - name: isort
      run: isort --check .
    - name: flake8
      run: flake8

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django-version: [2.2, 3.1, 3.2, 4.0]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: pip install "Django~=${{ matrix.django-version }}.0" 'contextvars;python_version<"3.7"'
    - name: Run Tests
      run: python manage.py test
